export const SWITCH_BLOCK_TYPE = "SWITCH_BLOCK_TYPE";
export const SELECT_BLOCK = "SELECT_BLOCK";
export const ADD_BLOCK = "ADD_BLOCK";
export const REMOVE_BLOCK = "REMOVE_BLOCK";
export const CHANGE_BLOCK_TYPE = "CHANGE_BLOCK_TYPE";
